### ISSUE TITLE
Same issue

### ISSUE THREAD

**Issue by maelp** [motorro/BeforeSnapshot#1]
Hi @motorro I have the exact same issue as you, when using those libs

```
    "firebase-admin": "12.2.0",
    "firebase-functions": "4.9.0",
"protobufjs": "7.3.2",
```

any idea how you've fixed it?

**Comment by motorro** [comment]
@maelp, unfortunately I didn't fix it. I've made this repo as a bug-report for that issue you've already answered. Try to make some minimal repo like this and post there. Guys from firebase are friendly and fix issues promptly if you provide them with a reproducible bug.
